insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (1, 'Noach', 'Meak', 'Zaleszany', '37-415');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (2, 'Addison', 'Conen', 'Boudinar', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (3, 'Merilee', 'Durkin', 'Zhaocun', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (4, 'Birch', 'Landell', 'Houxi', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (5, 'Jorgan', 'Crumb', 'Zangkaxa', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (6, 'Nicky', 'Bengochea', 'Gi?ng Trôm', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (7, 'Crawford', 'Scardafield', 'Shijie', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (8, 'Floria', 'Danovich', 'Liji', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (9, 'Buddie', 'Haugg', 'Taiping', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (10, 'Nathalia', 'Carneck', 'Gushan', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (11, 'Allard', 'Scriver', 'Batticaloa', '30000');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (12, 'Val', 'Assender', 'Yangjia', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (13, 'Peggi', 'Sinott', 'Digdig', '9318');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (14, 'Hilary', 'Skipton', 'Newark', '07104');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (15, 'Josie', 'Dufour', 'Kawm ?am?dah', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (16, 'Reta', 'Thredder', 'Mah?b?d', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (17, 'Daren', 'Cyster', 'Rancakole', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (18, 'Thain', 'Battle', 'Xingxi', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (19, 'Brenda', 'Kiebes', 'Nankang', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (20, 'Lorrie', 'Dubs', 'Mengxingzhuang', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (21, 'Correy', 'Ashling', 'Qiqian', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (22, 'Kinsley', 'Bisatt', 'Guli', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (23, 'Alford', 'Creeboe', 'Santa Clara La Laguna', '07007');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (24, 'Chery', 'McAuslene', 'Taunoa', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (25, 'Ethe', 'D''Antonio', 'Bardaï', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (26, 'Jordanna', 'Zorzenoni', 'Busuanga', '5317');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (27, 'Stefanie', 'Elvidge', 'Liuji', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (28, 'Pierre', 'Beller', 'Curuan', '6511');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (29, 'Bentlee', 'Elby', 'At T?j', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (30, 'Jake', 'Mollnar', 'Gajah', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (31, 'Megan', 'Plessing', 'Pelópion', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (32, 'Hilliary', 'Cheeseman', 'F?man', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (33, 'Lib', 'Burgon', 'Bemposta', '4730-010');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (34, 'Brnaby', 'Sallows', 'Rominimbang', '9614');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (35, 'Torrey', 'Scading', 'Batobato', '1091');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (36, 'Swen', 'Olensby', 'Bulacan', '3017');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (37, 'Reed', 'McConaghy', 'Jincheng', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (38, 'Martino', 'Vanyutin', 'Kolonowskie', '47-113');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (39, 'Chrysler', 'Twitchett', 'Banqiao', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (40, 'Lin', 'Holgan', 'Trujillo', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (41, 'Frankie', 'Bratcher', 'Dolní Dvo?išt?', '382 72');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (42, 'Herta', 'Lahy', 'Yuetang', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (43, 'Kele', 'Elcott', 'Shuitian', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (44, 'Calhoun', 'Bifield', 'Gubu', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (45, 'Avrom', 'Bridgwood', 'Souziqiu', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (46, 'Sinclare', 'Eplate', 'Kampungbajo', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (47, 'Jolie', 'Brunker', 'Mocun', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (48, 'Baron', 'Cosins', 'Dzyarzhynsk', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (49, 'Almire', 'Vescovini', 'Lazo', '692980');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (50, 'Marcellina', 'Anders', 'Ampatuan', '9609');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (51, 'Oralle', 'Buchanan', 'Tongshanxiang', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (52, 'Andi', 'MacKaig', 'Seren Barat', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (53, 'Adena', 'Creak', 'Pondokrejo Wetan', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (54, 'Waiter', 'Giacopazzi', 'Hongjiazui', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (55, 'Shanan', 'Elkin', 'Khawr Maksar', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (56, 'Hardy', 'Cochran', 'Esparza', '60201');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (57, 'Estell', 'Perfili', 'Koronowo', '86-010');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (58, 'Terence', 'Umbert', 'Tangwei', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (59, 'Timotheus', 'MacFadyen', 'Wonokerto', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (60, 'Nicolette', 'Vaan', 'Guanshan', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (61, 'Franni', 'Hizir', 'Karangtengah', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (62, 'Elliot', 'Grindall', 'Bar-le-Duc', '55013 CEDEX');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (63, 'Zacherie', 'Stelli', 'Oxford', 'K7A');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (64, 'Marylin', 'Denniston', 'Faisal?b?d', '48101');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (65, 'Bevon', 'Gundrey', 'Caoping', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (66, 'Gearard', 'Tramel', 'München', '81543');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (67, 'Quinton', 'Mucklestone', 'Imulolong', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (68, 'Stacy', 'Wastie', 'Samangawah', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (69, 'Damaris', 'Bruntje', 'Abakaliki', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (70, 'Stace', 'Brosoli', 'Miranda', '191529');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (71, 'Marylinda', 'Bazoche', 'Grebnevo', '141160');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (72, 'Matthieu', 'Ellor', 'Gjirokastër', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (73, 'Pryce', 'Gowling', 'København', '1201');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (74, 'Dedra', 'Dorwood', 'Gongnong', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (75, 'Kippy', 'Braden', 'Negotino', '1440');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (76, 'Lelah', 'Spaduzza', 'Quiling', '2902');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (77, 'Appolonia', 'Beal', 'Ili', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (78, 'Marven', 'Phillot', 'Shapa', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (79, 'Loreen', 'Orhtmann', 'Fubei', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (80, 'Eleni', 'Lars', 'Conchopata', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (81, 'Allen', 'Mitkcov', 'Thessaloníki', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (82, 'Juana', 'Youthead', 'Luau', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (83, 'Sileas', 'Leasor', 'Yingpu', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (84, 'Leia', 'Abrami', 'Niederanven', 'L-6948');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (85, 'Meggy', 'Bruckmann', 'København', '1738');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (86, 'Brennen', 'Vooght', 'Palompon', '6538');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (87, 'Laryssa', 'MacArthur', 'Batusangkar', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (88, 'Liam', 'Hebburn', 'Ujar', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (89, 'Felicio', 'Legrice', 'Toulon', '83087 CEDEX 9');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (90, 'Darla', 'Cutts', 'Bhakkar', '30001');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (91, 'Jamesy', 'Tilt', 'Woto', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (92, 'Chiarra', 'Flaune', 'Tabon', '6710');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (93, 'Myrtie', 'Queree', 'Wanzu', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (94, 'Didi', 'Methringham', 'Mar?veh Tappeh', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (95, 'Beale', 'Bigham', 'Datarnangka', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (96, 'Aleksandr', 'Newlan', '??????', '1225');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (97, 'Broderick', 'Daud', 'Varnávas', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (98, 'Melanie', 'MacAlees', 'Batang', null);
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (99, 'Mahmoud', 'Domesday', 'Sundumbili', '9334');
insert into cinemaplace (id_cinemaplace, name, adress, city, cp) values (100, 'Morgen', 'Meffen', 'Laya', '3107');