insert into movie (id_movie , title, resume, duration) values (1, 'Omar', 'Drama|Romance', '120');
insert into movie (id_movie , title, resume, duration) values (2, 'Kotch', 'Comedy|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (3, 'Riddick', 'Action|Sci-Fi|Thriller|IMAX', '120');
insert into movie (id_movie , title, resume, duration) values (4, 'Beautiful Creatures', 'Comedy|Crime|Drama|Thriller', '120');
insert into movie (id_movie , title, resume, duration) values (5, 'Glass Key, The', 'Crime|Drama|Film-Noir|Mystery', '180');
insert into movie (id_movie , title, resume, duration) values (6, 'Rebirth of Mothra III', 'Action|Fantasy|Sci-Fi', '180');
insert into movie (id_movie , title, resume, duration) values (7, 'Stander', 'Action|Crime|Drama', '180');
insert into movie (id_movie , title, resume, duration) values (8, 'Carnosaur', 'Horror|Sci-Fi', '180');
insert into movie (id_movie , title, resume, duration) values (9, 'Time Regained (Temps retrouvé, Le)', 'Drama', '180');
insert into movie (id_movie , title, resume, duration) values (10, 'Hip Hop Witch, Da', 'Comedy|Horror|Thriller', '360');
insert into movie (id_movie , title, resume, duration) values (11, 'First Target', 'Action', '60');
insert into movie (id_movie , title, resume, duration) values (12, 'Precious', 'Drama', '60');
insert into movie (id_movie , title, resume, duration) values (13, 'I Remember (Eu Me Lembro)', 'Drama', '60');
insert into movie (id_movie , title, resume, duration) values (14, '18 Years Old and Rising (J''aime regarder les filles)', 'Comedy', '60');
insert into movie (id_movie , title, resume, duration) values (15, 'Def-Con 4', 'Action|Sci-Fi', '60');
insert into movie (id_movie , title, resume, duration) values (16, 'Halloween II', 'Horror|Thriller', '120');
insert into movie (id_movie , title, resume, duration) values (17, 'Reel Rock 8 ', 'Documentary', '120');
insert into movie (id_movie , title, resume, duration) values (18, 'Stand and Deliver', 'Comedy|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (19, 'Anna Karenina', 'Drama|Romance', '120');
insert into movie (id_movie , title, resume, duration) values (20, 'Bank Error in Your Favour (Erreur de la banque en votre faveur)', 'Comedy', '120');
insert into movie (id_movie , title, resume, duration) values (21, 'Into the Abyss', 'Documentary', '120');
insert into movie (id_movie , title, resume, duration) values (22, 'Marc Pease Experience, The', 'Comedy|Drama|Musical', '120');
insert into movie (id_movie , title, resume, duration) values (23, 'Fool for Love', 'Drama', '120');
insert into movie (id_movie , title, resume, duration) values (24, 'Osterman Weekend, The', 'Action|Thriller', '120');
insert into movie (id_movie , title, resume, duration) values (25, 'In Search of a Midnight Kiss', 'Comedy|Romance', '180');
insert into movie (id_movie , title, resume, duration) values (26, 'Affair of the Necklace, The', 'Drama', '180');
insert into movie (id_movie , title, resume, duration) values (27, 'My Date with Drew', 'Comedy|Documentary|Romance', '180');
insert into movie (id_movie , title, resume, duration) values (28, 'EMR', 'Thriller', '180');
insert into movie (id_movie , title, resume, duration) values (29, 'Confessions of a Burning Man', 'Documentary', '180');
insert into movie (id_movie , title, resume, duration) values (30, 'Museum Hours', 'Drama', '180');
insert into movie (id_movie , title, resume, duration) values (31, 'Respiro', 'Comedy|Drama', '180');
insert into movie (id_movie , title, resume, duration) values (32, 'Magic of Méliès, The (magie Méliès, La)', 'Documentary', '180');
insert into movie (id_movie , title, resume, duration) values (33, 'Shark Night 3D', 'Horror|Thriller', '180');
insert into movie (id_movie , title, resume, duration) values (34, 'White Dwarf, The (Valkoinen kääpiö)', 'Drama', '120');
insert into movie (id_movie , title, resume, duration) values (35, 'Deliverance Creek', 'Drama', '120');
insert into movie (id_movie , title, resume, duration) values (36, 'Tar', 'Drama', '120');
insert into movie (id_movie , title, resume, duration) values (37, 'The Thirteen Assassins', 'Action|Adventure', '120');
insert into movie (id_movie , title, resume, duration) values (38, 'Deep Sea 3D', 'Documentary|IMAX', '120');
insert into movie (id_movie , title, resume, duration) values (39, 'Nukes in Space', 'Documentary', '120');
insert into movie (id_movie , title, resume, duration) values (40, 'Nancy Drew', 'Adventure|Crime|Thriller', '120');
insert into movie (id_movie , title, resume, duration) values (41, 'Red', 'Action|Comedy', '120');
insert into movie (id_movie , title, resume, duration) values (42, 'Spencer''s Mountain', 'Comedy|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (43, 'Chris Rock: Bigger & Blacker', 'Comedy', '120');
insert into movie (id_movie , title, resume, duration) values (44, 'Kolya (Kolja)', 'Comedy|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (45, 'Battleship', 'Action|Sci-Fi|Thriller|IMAX', '120');
insert into movie (id_movie , title, resume, duration) values (46, 'Little Fugitive', 'Drama', '120');
insert into movie (id_movie , title, resume, duration) values (47, 'The New Babylon', 'Drama', '120');
insert into movie (id_movie , title, resume, duration) values (48, 'All About Actresses (Le bal des actrices)', 'Comedy|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (49, 'Santa''s Slay', 'Comedy|Fantasy|Horror', '120');
insert into movie (id_movie , title, resume, duration) values (50, 'Trial, The (Procès, Le)', 'Drama', '120');
insert into movie (id_movie , title, resume, duration) values (51, 'Fitna', 'Documentary', '120');
insert into movie (id_movie , title, resume, duration) values (52, 'Inquisitor, The (a.k.a. Under Suspicion) (Garde à vue)', 'Crime|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (53, 'Jubilation Street', '(no genres listed)', '120');
insert into movie (id_movie , title, resume, duration) values (54, 'Adore', 'Drama|Romance', '120');
insert into movie (id_movie , title, resume, duration) values (55, 'Alexandra (Aleksandra)', 'Drama|War', '120');
insert into movie (id_movie , title, resume, duration) values (56, 'McCullin', 'Documentary', '120');
insert into movie (id_movie , title, resume, duration) values (57, 'American Tail, An', 'Adventure|Animation|Children|Comedy', '120');
insert into movie (id_movie , title, resume, duration) values (58, 'Drifting Clouds (Kauas pilvet karkaavat)', 'Comedy|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (59, 'Breakheart Pass', 'Western', '120');
insert into movie (id_movie , title, resume, duration) values (60, 'Ghost Dad', 'Comedy|Fantasy', '120');
insert into movie (id_movie , title, resume, duration) values (61, 'Competition, The', 'Drama|Romance', '120');
insert into movie (id_movie , title, resume, duration) values (62, 'Kiss Me Kate', 'Comedy|Musical|Romance', '120');
insert into movie (id_movie , title, resume, duration) values (63, 'Love Stinks', 'Comedy', '120');
insert into movie (id_movie , title, resume, duration) values (64, 'Waiting Room, The', 'Documentary', '180');
insert into movie (id_movie , title, resume, duration) values (65, 'Stepfather II', 'Horror|Thriller', '120');
insert into movie (id_movie , title, resume, duration) values (66, 'Madhouse', 'Horror|Thriller', '120');
insert into movie (id_movie , title, resume, duration) values (67, 'Candidate, The (Kandidaten)', 'Thriller', '60');
insert into movie (id_movie , title, resume, duration) values (68, 'Fly, The', 'Horror|Mystery|Sci-Fi', '120');
insert into movie (id_movie , title, resume, duration) values (69, 'God Is the Bigger Elvis', 'Documentary', '120');
insert into movie (id_movie , title, resume, duration) values (70, 'Hitler''s Stealth Fighter', 'Documentary', '120');
insert into movie (id_movie , title, resume, duration) values (71, 'Big Buck Bunny', 'Animation|Comedy', '120');
insert into movie (id_movie , title, resume, duration) values (72, 'India: Matri Bhumi', 'Documentary|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (73, 'On the Road', 'Adventure|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (74, 'Film ist. 7-12', 'Documentary', '120');
insert into movie (id_movie , title, resume, duration) values (75, 'Happy Poet, The', 'Comedy|Drama|Romance', '120');
insert into movie (id_movie , title, resume, duration) values (76, 'Alias the Doctor', 'Drama', '120');
insert into movie (id_movie , title, resume, duration) values (77, 'Dr. Dolittle 3', 'Children|Comedy|Fantasy', '120');
insert into movie (id_movie , title, resume, duration) values (78, 'Benny & Joon', 'Comedy|Romance', '120');
insert into movie (id_movie , title, resume, duration) values (79, 'Invasion U.S.A.', 'Action|Thriller', '120');
insert into movie (id_movie , title, resume, duration) values (80, 'Melinda and Melinda', 'Comedy|Drama', '120');
insert into movie (id_movie , title, resume, duration) values (81, 'Midnight Dancers (Sibak)', 'Comedy|Drama', '60');
insert into movie (id_movie , title, resume, duration) values (82, 'Fanny and Alexander (Fanny och Alexander)', 'Drama|Fantasy|Mystery', '60');
insert into movie (id_movie , title, resume, duration) values (83, 'Great Lie, The', 'Drama', '60');
insert into movie (id_movie , title, resume, duration) values (84, 'Kairat', 'Drama', '60');
insert into movie (id_movie , title, resume, duration) values (85, 'Street Thief', 'Crime|Documentary', '60');
insert into movie (id_movie , title, resume, duration) values (86, 'Hiding Out', 'Comedy', '60');
insert into movie (id_movie , title, resume, duration) values (87, 'Sarah Silverman:  We Are Miracles', 'Comedy', '60');
insert into movie (id_movie , title, resume, duration) values (88, 'Long Voyage Home, The', 'Drama|War', '60');
insert into movie (id_movie , title, resume, duration) values (89, 'Boy (Shônen)', 'Drama', '60');
insert into movie (id_movie , title, resume, duration) values (90, '20,000 Leagues Under the Sea', 'Adventure|Romance|Sci-Fi', '60');
insert into movie (id_movie , title, resume, duration) values (91, 'RocketMan (a.k.a. Rocket Man)', 'Children|Comedy|Romance|Sci-Fi', '60');
insert into movie (id_movie , title, resume, duration) values (92, 'Chu Chin Chow', 'Comedy|Fantasy|Musical', '60');
insert into movie (id_movie , title, resume, duration) values (93, 'The Swedish Moment', 'Comedy', '60');
insert into movie (id_movie , title, resume, duration) values (94, 'Twelve Angry Men', 'Drama', '60');
insert into movie (id_movie , title, resume, duration) values (95, 'Wyvern', 'Horror|Sci-Fi|Thriller', '60');
insert into movie (id_movie , title, resume, duration) values (96, 'Map For Saturday, A', 'Documentary', '60');
insert into movie (id_movie , title, resume, duration) values (97, 'An American Tail: The Treasure of Manhattan Island', 'Adventure|Animation', '60');
insert into movie (id_movie , title, resume, duration) values (98, 'Road House', 'Action|Drama', '60');
insert into movie (id_movie , title, resume, duration) values (99, 'Caramel (Sukkar banat)', 'Comedy', '60');
insert into movie (id_movie , title, resume, duration) values (100, 'Wind Rises, The (Kaze tachinu)', 'Animation|Drama|Romance', '60');